platform:
  - x64
  
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - node -v
  - npm -v
  - npm prune
  - npm install
  
build_script:
  - node --version
  - npm --version
  - npm run dist
  - dir %APPVEYOR_BUILD_FOLDER%\dist\win-x64
  
artifacts:
  - path: dist\*.exe
  - type: Auto

test: off