platform:
  - x64
  
on:
  branch: master                 # release from master branch only
  appveyor_repo_tag: true        # deploy on tag push only
  
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: 3fb3abba2b6fc32212b9c134da6705ab8661dd38

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - node -v
  - npm -v
  - npm prune
  - npm install
  
build_script:
  - node --version
  - npm --version
  - npm run dist
  - dir %APPVEYOR_BUILD_FOLDER%\dist\win-x64
  
artifacts:
  - path: dist\win-x64\*
    name: WindowsInstall

test: off